### ISSUE TITLE
Inference speed on python vs cpp ?

### ISSUE THREAD

**Issue by adesgautam** [doleron/yolov4-opencv-cpp-python#1]
Hi, do you have any comparison for the inference speed between cpp & python with batch 1 ?
It would be very helpful if you have any such metrics.

Have a good day!

**Comment by doleron** [comment]
Hi,

at some moment, I did a mistake and my C++ code were slower than my same Python code using CUDA. I realized it was a stupid mistake in my code so I fixed it.

You can use this repo to run C++ and Python code and compare the performances: https://github.com/doleron/yolov4-opencv-cpp-python-perf
Let me know if you find any problems.
